name: Test Deployment

on:
  push:
    branches:
      - test

env:
  MONGO_URL: ValueFakeToTest
  API_GATEWAY_PORT: 6000
  CAD_SERVICE_PORT: 5002
  CAD_SERVICE_HOST: localhost
  ACAO_SERVICE_PORT: 5001
  ACAO_SERVICE_HOST: localhost
  AUTH_SERVICE_PORT: 4010
  AUTH_SERVICE_HOST: localhost
  ADM_URL: localhost:4000/api/v1/
  ADM_USER: userFake
  ADM_PASSWD=: passFake

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['6.0']

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile      
              
    - name: Running testing
      run: yarn test